-- Create the APP_CONFIG table
CREATE TABLE APP_CONFIG (
    CONFIG_ID VARCHAR2(12) NOT NULL,
    CONFIG_KEY VARCHAR2(100) NOT NULL,
    CONFIG_VALUE NVARCHAR2(500) NOT NULL,
    DESCRIPTION NVARCHAR2(1000),
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_APP_CONFIG PRIMARY KEY (CONFIG_ID),
    CONSTRAINT UK_APP_CONFIG_KEY UNIQUE (CONFIG_KEY),
    CONSTRAINT CHK_APP_CONFIG_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

-- Create index for better query performance
CREATE INDEX IDX_APP_CONFIG_ACTIVE ON APP_CONFIG(IS_ACTIVE);
CREATE INDEX IDX_APP_CONFIG_UPDATED ON APP_CONFIG(UPDATED_AT);

-- Create sequence with optimal settings
CREATE SEQUENCE APP_CONFIG_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 50  -- Better performance than NOCACHE
    NOCYCLE
    ORDER;

-- Create trigger for ID generation (alternative approach)
CREATE OR REPLACE TRIGGER APP_CONFIG_BI
BEFORE INSERT ON APP_CONFIG
FOR EACH ROW
BEGIN
    IF :NEW.CONFIG_ID IS NULL THEN
        SELECT 'CONF' || LPAD(APP_CONFIG_SEQ.NEXTVAL, 8, '0')
        INTO :NEW.CONFIG_ID
        FROM DUAL;
    END IF;

    -- Force consistent timestamps
    :NEW.CREATED_AT := SYSTIMESTAMP;
END;
/

-- Create trigger for update timestamp
CREATE OR REPLACE TRIGGER APP_CONFIG_BU
BEFORE UPDATE ON APP_CONFIG
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/


-- Comments for documentation
COMMENT ON TABLE APP_CONFIG IS 'Stores application configuration parameters';
COMMENT ON COLUMN APP_CONFIG.CONFIG_ID IS 'Primary key in CONFIG000001 format';
COMMENT ON COLUMN APP_CONFIG.CONFIG_KEY IS 'Unique configuration key';
COMMENT ON COLUMN APP_CONFIG.CONFIG_VALUE IS 'Configuration value';
COMMENT ON COLUMN APP_CONFIG.DESCRIPTION IS 'Description of the configuration';
COMMENT ON COLUMN APP_CONFIG.CREATED_AT IS 'Timestamp when record was created';
COMMENT ON COLUMN APP_CONFIG.UPDATED_AT IS 'Timestamp when record was last updated';
COMMENT ON COLUMN APP_CONFIG.IS_ACTIVE IS 'Soft delete flag (1=active, 0=inactive)';


