CREATE TABLE USER_ACCOUNT (
    USER_ID VARCHAR2(12) PRIMARY KEY,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL,
    PHONE_NUMBER VARCHAR2(20) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6),
    CONSTRAINT UK_USER_ACCOUNT_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_USER_ACCOUNT_PHONE_NUMBER UNIQUE (PHONE_NUMBER),
    CONSTRAINT CHK_USER_ACCOUNT_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);


-- Indexes
CREATE INDEX IDX_USER_ACCOUNT_NAME ON USER_ACCOUNT(LAST_NAME, FIRST_NAME);
CREATE INDEX IDX_USER_ACCOUNT_ACTIVE ON USER_ACCOUNT(IS_ACTIVE);

-- Sequence for ID generation
CREATE SEQUENCE USER_ACCOUNT_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    NOCYCLE
    ORDER;

-- Trigger for ID generation
CREATE OR REPLACE TRIGGER USER_ACCOUNT_BI
BEFORE INSERT ON USER_ACCOUNT
FOR EACH ROW
BEGIN
    IF :NEW.USER_ID IS NULL THEN
        SELECT 'USER' || LPAD(USER_ACCOUNT_SEQ.NEXTVAL, 8, '0')
        INTO :NEW.USER_ID
        FROM DUAL;
    END IF;

    -- Force consistent timestamps
    :NEW.CREATED_AT := SYSTIMESTAMP;
END;
/

-- Create trigger for update timestamp
CREATE OR REPLACE TRIGGER USER_ACCOUNT_BU
BEFORE UPDATE ON USER_ACCOUNT
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/


-- Table and Column Comments
COMMENT ON TABLE USER_ACCOUNT IS 'Stores user information and work details';
COMMENT ON COLUMN USER_ACCOUNT.USER_ID IS 'Primary key in USER0000000001 format';
COMMENT ON COLUMN USER_ACCOUNT.FIRST_NAME IS 'User first name';
COMMENT ON COLUMN USER_ACCOUNT.LAST_NAME IS 'User last name';
COMMENT ON COLUMN USER_ACCOUNT.PASSWORD IS 'User account password';
COMMENT ON COLUMN USER_ACCOUNT.EMAIL IS 'Official work email address (unique)';
COMMENT ON COLUMN USER_ACCOUNT.PHONE_NUMBER IS 'Contact phone number (unique)';
COMMENT ON COLUMN USER_ACCOUNT.IS_ACTIVE IS 'User account status (1=active, 0=inactive)';
COMMENT ON COLUMN USER_ACCOUNT.CREATED_AT IS 'Timestamp when record was created';
COMMENT ON COLUMN USER_ACCOUNT.UPDATED_AT IS 'Timestamp when record was last updated';
